site_name: DMP Evaluation Service
site_description: Documentation and simple web UI for the DMP evaluation service
site_url: https://example.com
repo_url: https://github.com/OSTrails/DMP-Evaluation-Service

theme:
  name: material
  custom_dir: overrides 
  language: en
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: blue
      accent: grey
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: grey

extra:
  # 👇 Change this to your API’s base URL (dev/prod)
  api_base_url: "http://localhost:8080"
  contact_email: "you@example.com"

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra_javascript:
  - assets/javascripts/config.js
  - assets/javascripts/utils.js
  - assets/javascripts/components.js 
  - assets/javascripts/benchmarks.js
  - assets/javascripts/evaluate.js
  - assets/javascripts/status_lists.js
  - assets/javascripts/main.js

extra_css:
  - assets/stylesheets/extra.css

nav:
  - Home: index.md
  - Evaluate: evaluate.md
  - List of Entities: status.md
  - API: api.md
